spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: 123456
#    url: jdbc:mysql://101.37.32.91:3305/sell?allowPublicKeyRetrieval=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: LIyt060912
    url: jdbc:mysql://localhost:3306/sell?allowPublicKeyRetrieval=true&characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
server:
  servlet:
    context-path: /sell
